unionai-oss/unionml

flytekit_learn/dataset.py
requirements-dev.txt
tests/unit/test_sqltask_reader.py

fixes https://github.com/unionai-oss/flytekit-learn/issues/9

add support for Dataset.from_sqlalchemy

---

flytekit_learn/dataset.py
flytekit_learn/model.py
flytekit_learn/utils.py
tests/unit/test_dataset.py
tests/unit/test_model.py

add support for custom splitter and parser functions

---

.github/workflows/publish.yml
setup.py

Added CI for pypi publish automation 
Test: https://github.com/unionai-oss/unionml/runs/6199458458?check_suite_focus=true
https://pypi.org/project/unionml/0.0.1/

feat: added ci for publishing pypi package

---

aws-lambda-example/README.md
docs/source/local_app.md
tests/integration/api_requests.py
tests/integration/test_fastapi.py
unionml/fastapi.py
unionml/model.py
unionml/remote.py

remove the local fastapi serving param

---

docs/source/conf.py
docs/source/dataset.md
docs/source/deploying.md
docs/source/flyte_cluster.md
docs/source/index.md
docs/source/local_app.md
docs/source/serving_aws_lambda.md
docs/source/serving_fastapi.md
docs/source/user_guide.md

Fixes https://github.com/unionai-oss/unionml/issues/67

docs fixes

---

docs/source/dataset.md
docs/source/flyte_cluster.md
docs/source/index.md
docs/source/user_guide.md
tests/unit/test_aws_lambda_handler.py
tests/unit/test_dataset.py
unionml/cli.py
unionml/dataset.py
unionml/fastapi.py
unionml/model.py

- implement `dataset.loader` function: this is an optional function to handle cases where the output of `reader` is in some format that needs to be deserialized and loaded into memory
- implement `dataset.feature_loader`: similar to `loader` but this is used for deserializing features data or converting from a raw format on the prediction side of things.
- implement `dataset.feature_transformer`: a function applied to the output of `feature_loader`, for further data processing
- Add `feature_key` to `dataset.parser` so that user can indicate position of the features in the `parser` function output
- Updated docs.

Clean up dataset

---

README.md

Accuracy_score wasn't being identified.
Signed-off-by: SmritiSatyanV <smriti@union.ai>

Add accuracy_score metric's library

---

setup.py

Fix templates

---

.gitattributes
.github/workflows/publish.yml
MANIFEST.in
requirements.txt
setup.py
unionml/__init__.py

The source is missing `requirements.txt`. This PR will ensure such slip-ups are avoided by design with minimal maintenance in future.
- Explicitly specify files/folders to include or exclude from the PyPI source (`unionml-#.#.#.tar.gz` file).
- This also helps separate the concern of what to package in the PyPI source from the rest of the logic in `setup.py` .

Update source packaging

---

.github/workflows/build.yml
docs/notebooks/mnist.ipynb
docs/notebooks/quickdraw.ipynb
docs/source/tutorials/mnist.md
docs/source/tutorials/quickdraw.md
unionml/cli.py
unionml/templates/quickdraw/cookiecutter.json
unionml/templates/quickdraw/hooks
unionml/templates/quickdraw/{{cookiecutter.app_name}}/.gitignore
unionml/templates/quickdraw/{{cookiecutter.app_name}}/Dockerfile
unionml/templates/quickdraw/{{cookiecutter.app_name}}/README.md
unionml/templates/quickdraw/{{cookiecutter.app_name}}/app.py
unionml/templates/quickdraw/{{cookiecutter.app_name}}/helpers.py
unionml/templates/quickdraw/{{cookiecutter.app_name}}/quickdraw/dataset.py
unionml/templates/quickdraw/{{cookiecutter.app_name}}/quickdraw/model.py
unionml/templates/quickdraw/{{cookiecutter.app_name}}/requirements.txt
unionml/utils.py

Create a template for the quickdraw ML application

quickdraw template

---

requirements.txt
tests/unit/test_model.py
unionml/__init__.py
unionml/dataset.py
unionml/model.py

feature/98: support Dataset loader, splitter and parser kwargs in Model.trainer

---

tests/unit/test_dataset.py
tests/unit/test_type_guards.py
unionml/dataset.py
unionml/fastapi.py
unionml/model.py
unionml/type_guards.py

implement type guards for function decorators

---

unionml/cli.py
unionml/fastapi.py
unionml/model.py

add wait to train and predict cli, use model_type hint

---

requirements.txt
tests/integration/test_fastapi.py
unionml/fastapi.py
unionml/model.py

add app_version to serving, fix integration tests

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Added COC and Contributing

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/config.yml
unionml/model.py

It is used when someone creates a blank issue and doesn't choses any issue templates.
It's very helpful :)
cc @cosmicBboy

Default Issue Template

---

tests/unit/test_sqltask_reader.py

Signed-off-by: Eduardo Apolinario <eapolinario@users.noreply.github.com>

Write sql statement in a single line

---

.github/PULL_REQUEST_TEMPLATE.md

Closes #191 
I have added the PR template for this repo.
cc @eapolinario and @cosmicBboy 
<a href="https://gitpod.io/#https://github.com/unionai-oss/unionml/pull/194"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

💡 feat: Add PULL REQUEST TEMPLATE

---

README.md

Now a user can go to unionml offical website with a single click. Minor but impactful.
<a href="https://gitpod.io/#https://github.com/unionai-oss/unionml/pull/196"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Hyperlinking unionml logo with offical website.

---

docs/source/contributing_guide.md

The integration tests are run with `pytest` not `python`. Patched straight from the edit button on the docs
<a href="https://gitpod.io/#https://github.com/unionai-oss/unionml/pull/199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Contributing guide integration test command

---

docs/source/scheduling.md

fixes scheduling docs inaccuracies

fix scheduling docs

---

docs/notebooks/mnist.ipynb
docs/notebooks/quickdraw.ipynb
docs/source/advanced_guides.md
docs/source/callbacks.md
docs/source/tutorials/mnist.md
docs/source/tutorials/quickdraw.md
tests/unit/test_aws_lambda_handler.py
unionml/model.py

Add documentation for the callbacks feature #195

add documentation for callbacks
